
github:
  prebuilds:
    master: true
    branches: true
image: ghcr.io/mike-seagull/gitpod-base:master
tasks:
  - name: install dependencies
    init: test -f go.mod
    command: go mod download
  - name: install goreleaser
    command: brew install goreleaser
vscode:
  extensions:
    - wayou.vscode-todo-highlight